---
- hosts: all
  become: true

  tasks:
    - name: Create Text File with Timestamp
      command: touch /home/vagrant/{{ ansible_date_time.date }}.txt
      ignore_errors: yes

    - name: Install software (Debian-based OS)
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
            - nginx
      register: update

    - name: Log update
      ansible.builtin.debug:
        var: update.stdout

    - name: Create Cron Job for Regular Cleanup
      cron:
        name: "Regular Cleanup"
        minute: "0"
        hour: "1"
        job: "find /tmp -type f -mtime +7 -delete"
        state: present
      register: cron

    - name: Log cron
      ansible.builtin.debug:
        var: cron.stdout
